name: CIPP Frontend Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'tinyskapie/CIPP'
    name: Build and Upload CIPP Frontend
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # Set up Node.js
      - name: Get Node version
        id: get_node_version
        run: |
          node_raw_version=$(node -p "require('./package.json').engines.node")
          node_sanitized_version=$(echo $node_raw_version | sed -E 's/[^0-9.]+//g')
          echo "node_version=$node_sanitized_version" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ steps.get_node_version.outputs.node_version }}

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the project
      - name: Build Project
        run: npm run build

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "out"
          api_location: ""
          output_location: ""
